# Generated by Django 4.2.3 on 2023-07-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_word', models.CharField(max_length=100, verbose_name='Слово')),
                ('player_points', models.IntegerField(verbose_name='Очки игрока')),
                ('comp_points', models.IntegerField(verbose_name='Очки компьютера')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слова')),
            ],
        ),
    ]
